### PR TITLE
Add `if_else`

### PR DESCRIPTION
**Pull request by MarcoWorms**
I use this so much when I'm doing stuff with ramda, so here goes another additions suggestion :D

I also want to add `cond` but I'm doing this one before because I don't know if you are trying to redo ramda here xD

### CODE REVIEW

**Comment by harmenjanssen** [comment]
Oh! But look at `when`: https://github.com/grrr-amsterdam/garp-functional/blob/master/library/Garp/Functional/When.php

`when` is `if_else`!

**Comment by MarcoWorms** [comment]
Oh, thanks! Is `cond` also implemented with another name? If not, shall i do it?

**Comment by harmenjanssen** [comment]
I have not implemented `cond` yet (I actually did not know it), but that would be a very welcome addition to the library! 

I will happily accept `cond` as a pull request.

**Comment by MarcoWorms** [comment]
I'll do it then :D

**Pull request closed without merging**
