### PR TITLE
PHPStan and type improvements

### PR DESCRIPTION
**Pull request by martijngastkemper**
Garp Functional causes a lot of PHPStan errors in projects. But I think it's possible to solve a lot of them. For example last year they introduced conditional return types: https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types

This PR introduced PHPStan level 9 validation. It's still a huge baseline file, but it's a start.

### CODE REVIEW

**Comment by harmenjanssen** [comment]
Oh, wow, those conditional return types look very promising! 
That will definitely solve a lot of issues. Most stuff I ran into was caused by the functions being curried.

**Comment by martijngastkemper** [comment]
~The PHPStan check fails, but it doesn't on my computer. Can you try to run PHPstan on your machine with PHP 8.2?~

I've found the problem. This branch wasn't up to date with `main`.

**Comment by harmenjanssen** [comment]
For what it's worth, on my computer the build is green with PHP 8.2!

**Comment by martijngastkemper** [comment]
I think this PR is ready for merge. It drops PHP 7.1 support, so it will become version 6.0. I want to merge #46 first, to release the last 5.0 version.

**Review by harmenjanssen — APPROVED** [review]
I agree, LGTM!

**Pull request merged**
